'use strict';
// CMP-PURCHASEKAIKEI-002: ドメイン層 — PostgreSQL 永続化・状態遷移ガード・履歴記録・発注番号採番
// v2: 内蔵会計エンジン（store/journal.js）で仕訳を自動計上。外部 API 依存なし。
//   検収 → 仕訳（借: 仕入高 5110 / 貸: 買掛金 2110）
//   支払 → 仕訳（借: 買掛金 2110 / 貸: 普通預金 1120）
// v4: SQLite 永続化（node:sqlite・7 テーブル・同一トランザクション）。
// v5: PostgreSQL に統一（1 サーバ 3 データベースの purchase DB。pg ドライバ・API は不変）。
//     pg は非同期 API のため全メソッドが async（v4 までの同期呼び出しからの置き換え）。
//     購買・支払予定・仕訳台帳・Outbox キューを同一トランザクションで書き込むため常に整合する。
//     旧 purchases.json（v3 以前）は初回起動時に自動取り込み（移行）する。
const fs = require('fs');
const path = require('path');
const { Client } = require('pg');
const { JournalEngine, ACCOUNTS_MASTER: ACCOUNTS_MASTER_LIST } = require('./journal');
const { KaikeiClient } = require('./kaikei-client');

// .env（app ルート）を読む — 依存を増やさないため 10 行で自前実装
// （DB パスワード等の接続情報はコミットしない — NFR-PURCHASEKAIKEI-001-05）
function loadDotEnv() {
  try {
    const envFile = path.join(__dirname, '..', '.env');
    for (const line of fs.readFileSync(envFile, 'utf8').split(/\r?\n/)) {
      const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/);
      if (m && process.env[m[1]] == null) process.env[m[1]] = m[2].replace(/^["']|["']$/g, '');
    }
  } catch {
    // .env が無い場合はプロセスの環境変数のみで動く
  }
}

const DDL = `
  CREATE TABLE IF NOT EXISTS counters (
    name  TEXT PRIMARY KEY,
    value INTEGER NOT NULL
  );
  CREATE TABLE IF NOT EXISTS purchases (
    id             TEXT PRIMARY KEY,
    item           TEXT    NOT NULL,
    qty            INTEGER NOT NULL,
    unit_price     DOUBLE PRECISION NOT NULL,
    amount         DOUBLE PRECISION NOT NULL,
    requester      TEXT    NOT NULL,
    department     TEXT    NOT NULL,
    note           TEXT    NOT NULL DEFAULT '',
    status         TEXT    NOT NULL,
    order_no       TEXT,
    received_total INTEGER NOT NULL DEFAULT 0,
    journal        JSONB   NOT NULL DEFAULT '[]', -- 仕訳参照（JSON）: NFR-003
    history        JSONB   NOT NULL DEFAULT '[]', -- 遷移履歴（JSON）
    correction     JSONB,                         -- v6 ステップ 5: 訂正申請の内容（承認待ちの間だけ保持）
    created_at     TEXT    NOT NULL
  );
  CREATE TABLE IF NOT EXISTS payables (
    id             TEXT PRIMARY KEY,
    purchase_id    TEXT    NOT NULL,
    purchase_item  TEXT    NOT NULL,
    department     TEXT    NOT NULL,
    received_qty   INTEGER NOT NULL,
    amount         INTEGER NOT NULL,
    received_date  TEXT,
    scheduled_date TEXT    NOT NULL,
    status         TEXT    NOT NULL,
    entry_id       INTEGER,                      -- 支払仕訳の entry id（AC-005-03）
    created_at     TEXT    NOT NULL,
    paid_at        TEXT
  );
  CREATE TABLE IF NOT EXISTS journal_entries (
    id              INTEGER PRIMARY KEY,
    date            TEXT NOT NULL,
    description     TEXT NOT NULL,
    department      TEXT NOT NULL,
    vendor_code     TEXT,                        -- v6 ステップ 8: 仕入先（マスタ参照）
    item_code       TEXT,                        -- v6 ステップ 8: 品目（マスタ参照）
    purchase_id     TEXT,                        -- v6 ステップ 4: 申請番号（購買 ↔ 仕訳の相互リンク用）
    voucher_no      TEXT,                        -- v6 ステップ 4: 元伝票番号（検収: PU-xxxx-Rn / 支払: PAY-xxxx）
    posted_by       TEXT,                        -- v6 ステップ 4: 計上者（操作者コード）
    entry_type      TEXT NOT NULL DEFAULT 'normal', -- normal / receive / pay / reversal / correction
    status          TEXT NOT NULL DEFAULT 'active', -- active / reversed（取消仕訳で取消された元仕訳）
    reverses_entry_id INTEGER,                   -- v6 ステップ 5: 取消対象の元仕訳（取消仕訳側に持つ）
    reversed_by     INTEGER,                     -- v6 ステップ 5: この仕訳を取消した取消仕訳（元仕訳側に持つ）
    kaikei_entry_id INTEGER,                     -- ミラー送信済みの kaikei-api 側 id
    created_at      TEXT NOT NULL
  );
  CREATE TABLE IF NOT EXISTS journal_lines (
    entry_id     INTEGER NOT NULL REFERENCES journal_entries (id),
    seq          INTEGER NOT NULL,
    account_code TEXT    NOT NULL,
    side         TEXT    NOT NULL,
    amount       INTEGER NOT NULL,
    PRIMARY KEY (entry_id, seq)
  );
  CREATE TABLE IF NOT EXISTS pending_links (
    seq            INTEGER PRIMARY KEY,          -- Outbox: 送信順を保持
    local_entry_id INTEGER NOT NULL,
    payload        JSONB   NOT NULL              -- kaikei-api 契約 §3 の形式
  );
  CREATE TABLE IF NOT EXISTS meta (
    key   TEXT PRIMARY KEY,
    value TEXT
  );
  CREATE TABLE IF NOT EXISTS users (
    code   TEXT PRIMARY KEY,
    name   TEXT    NOT NULL,
    role   TEXT    NOT NULL CHECK (role IN ('requester', 'approver', 'accounting', 'admin')),
    active INTEGER NOT NULL DEFAULT 1
  );
  CREATE TABLE IF NOT EXISTS vendors (
    code TEXT PRIMARY KEY,
    name TEXT    NOT NULL
  );
  CREATE TABLE IF NOT EXISTS items (
    code       TEXT PRIMARY KEY,
    name       TEXT    NOT NULL,
    unit_price INTEGER NOT NULL DEFAULT 0  -- 標準単価（申請フォームの初期値）
  );
  CREATE TABLE IF NOT EXISTS change_history (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_id TEXT   NOT NULL,                -- purchases.id
    changes   JSONB  NOT NULL,                -- [{ field, before, after }]
    actor     TEXT   NOT NULL,
    reason    TEXT   NOT NULL,
    at        TEXT   NOT NULL
  );
`;

const STATUSES = ['submitted', 'approved', 'rejected', 'ordered', 'received', 'paid', 'withdrawn', 'correction_pending'];
const DEPARTMENTS = ['D10', 'D20', 'D90'];

// 固定ユーザー（研修用。v6 ステップ 1: 操作者・ロール切替の源データ）
const USERS = [
  { code: 'u01', name: '劉 昱彤', role: 'requester' },
  { code: 'u02', name: '中村 洋一', role: 'approver' },
  { code: 'u03', name: '経理担当A', role: 'accounting' },
  { code: 'u99', name: 'Admin', role: 'admin' },
];

// 仕入先・品目のシード（研修用。マスタ画面から追加もできる）
const VENDORS = [
  { code: 'V001', name: 'オフィスワン商事' },
  { code: 'V002', name: 'テクノサプライ株式会社' },
  { code: 'V003', name: 'オンラインマーケット' },
];
const ITEMS = [
  { code: 'I001', name: 'コピー用紙 A4', unitPrice: 500 },
  { code: 'I002', name: 'トナーカートリッジ', unitPrice: 8000 },
  { code: 'I003', name: 'ノートPC', unitPrice: 120000 },
  { code: 'I004', name: 'デスクチェア', unitPrice: 25000 },
  { code: 'I005', name: 'ホワイトボード', unitPrice: 12000 },
];

class TransitionError extends Error {
  constructor(action, from) {
    super(`invalid_transition: ${action} is not allowed from "${from}"`);
    this.name = 'TransitionError';
    this.code = 'invalid_transition';
  }
}

// v6 ステップ 2: 自己承認禁止（AC 申請者本人の承認不可）
class SelfApprovalError extends Error {
  constructor() {
    super('この申請は本人が作成したため承認できません。');
    this.name = 'SelfApprovalError';
    this.code = 'self_approval';
  }
}

class ValidationError extends Error {
  constructor(message) {
    super(message);
    this.name = 'ValidationError';
    this.code = 'validation_error';
  }
}

function now() {
  return new Date().toISOString();
}

// 月末締め翌月末払い: 検収月の翌月末日を支払予定日とする
// 年月は文字列で扱い、タイムゾーンによる日ずれを防ぐ
function nextMonthEnd(dateStr) {
  const [y, m] = dateStr.split('-').map(Number);
  const ny = m === 12 ? y + 1 : y;
  const nm = m === 12 ? 1 : m + 1;
  const lastDay = new Date(Date.UTC(ny, nm, 0)).getUTCDate(); // 翌月 0 日 = 末日
  return `${ny}-${String(nm).padStart(2, '0')}-${String(lastDay).padStart(2, '0')}`;
}

class PurchaseStore {
  // 生成済みインスタンスの登録簿（テスト終了時の一括 close 用。pg の接続は
  // 開きっぱなしだと node --test のプロセスが終了しないため）
  static #live = new Set();

  // 非同期ファクトリ（PG 接続・スキーマ作成・hydrate・移行を済ませて返す）。
  // fresh: true はテスト用 — 既存データを全消しして空の状態から始める。
  static async create(dataDir, kaikei, { fresh = false } = {}) {
    const store = new PurchaseStore(dataDir, kaikei);
    await store.client.connect();
    PurchaseStore.#live.add(store);
    await store.client.query(DDL);
    // CREATE TABLE IF NOT EXISTS は既存テーブルに列を足さないため、足りない列だけ ALTER する
    // （研修用の簡易マイグレーション。列の追加のみで削除・型変更はしない）
    const expectedColumns = {
      purchases: [
        ['correction', 'JSONB'],
        ['vendor_code', 'TEXT'],
        ['item_code', 'TEXT'],
      ],
      journal_entries: [
        ['purchase_id', 'TEXT'],
        ['voucher_no', 'TEXT'],
        ['posted_by', 'TEXT'],
        ['entry_type', "TEXT NOT NULL DEFAULT 'normal'"],
        ['status', "TEXT NOT NULL DEFAULT 'active'"],
        ['reverses_entry_id', 'INTEGER'],
        ['reversed_by', 'INTEGER'],
      ],
      payables: [
        ['received_date', 'TEXT'],
      ],
    };
    for (const [table, cols] of Object.entries(expectedColumns)) {
      const existing = new Set(
        (await store.client.query('SELECT column_name FROM information_schema.columns WHERE table_name = $1', [table])).rows.map((r) => r.column_name),
      );
      for (const [name, def] of cols) {
        if (!existing.has(name)) await store.client.query(`ALTER TABLE ${table} ADD COLUMN ${name} ${def}`);
      }
    }
    if (fresh) {
      // テスト用の全消し。マスタ（vendors/items/users）も消すので、この直後に再投入する
      await store.client.query('TRUNCATE purchases, payables, journal_entries, journal_lines, pending_links, counters, meta, change_history, vendors, items, users');
    }
    // マスタは init 時に投入（冪等）。保存サイクルの対象外（users 以外は画面から追加可）
    for (const u of USERS) {
      await store.client.query(
        'INSERT INTO users (code, name, role, active) VALUES ($1, $2, $3, 1) ON CONFLICT (code) DO NOTHING',
        [u.code, u.name, u.role],
      );
    }
    for (const v of VENDORS) {
      await store.client.query('INSERT INTO vendors (code, name) VALUES ($1, $2) ON CONFLICT (code) DO NOTHING', [v.code, v.name]);
    }
    for (const it of ITEMS) {
      await store.client.query('INSERT INTO items (code, name, unit_price) VALUES ($1, $2, $3) ON CONFLICT (code) DO NOTHING', [it.code, it.name, it.unitPrice]);
    }
    await store.#hydrate();
    await store.#migrateJsonIfFresh();
    // 内蔵会計エンジン（entries 配列・counters を store と共有）
    store.journal = new JournalEngine(store.data.entries);
    store.journal.counters = store.data.counters;
    return store;
  }

  // kaikei: kaikei-api ミラー送信用クライアント（省略時は本物・テストではスタブを注入）。
  constructor(dataDir, kaikei) {
    loadDotEnv();
    this.dataDir = dataDir;
    this.kaikei = kaikei || new KaikeiClient();
    this.client = new Client({
      host: process.env.PG_HOST || 'localhost',
      port: Number(process.env.PG_PORT || 5432),
      user: process.env.PG_USER || 'postgres',
      password: process.env.PG_PASSWORD,
      database: process.env.PG_DATABASE || 'purchase',
    });
    this.data = { purchases: [], payables: [], entries: [], pendingLinks: [], counters: { purchase: 0, order: 0, payable: 0, entry: 0 }, users: [], vendors: [], items: [], changeHistory: [] };
  }

  /* ---------- PostgreSQL 永続化（v5） ---------- */

  // DB → メモリ（this.data）。形状は v3 までの JSON と同じ（既存テスト・ビュー互換）。
  // JSONB 列は pg が自動でオブジェクトにしてくれる（JSON.parse 不要）。
  async #hydrate() {
    const counters = { purchase: 0, order: 0, payable: 0, entry: 0 };
    for (const row of (await this.client.query('SELECT name, value FROM counters')).rows) {
      counters[row.name] = Number(row.value);
    }
    const purchases = (await this.client.query('SELECT * FROM purchases ORDER BY created_at, id')).rows.map((r) => ({
      id: r.id,
      item: r.item,
      qty: Number(r.qty),
      unitPrice: Number(r.unit_price),
      amount: Number(r.amount),
      requester: r.requester,
      department: r.department,
      note: r.note,
      vendorCode: r.vendor_code,
      itemCode: r.item_code,
      status: r.status,
      orderNo: r.order_no,
      receivedTotal: Number(r.received_total),
      journal: r.journal || [],
      history: r.history || [],
      correction: r.correction || null,
      createdAt: r.created_at,
    }));
    const payables = (await this.client.query('SELECT * FROM payables ORDER BY created_at, id')).rows.map((r) => ({
      id: r.id,
      purchaseId: r.purchase_id,
      purchaseItem: r.purchase_item,
      department: r.department,
      receivedQty: Number(r.received_qty),
      amount: Number(r.amount),
      receivedDate: r.received_date || null,
      scheduledDate: r.scheduled_date,
      status: r.status,
      entryId: r.entry_id == null ? null : Number(r.entry_id),
      createdAt: r.created_at,
      paidAt: r.paid_at,
    }));
    const linesByEntry = new Map();
    for (const l of (await this.client.query('SELECT entry_id, seq, account_code, side, amount FROM journal_lines ORDER BY entry_id, seq')).rows) {
      if (!linesByEntry.has(l.entry_id)) linesByEntry.set(l.entry_id, []);
      linesByEntry.get(l.entry_id).push({ account_code: l.account_code, side: l.side, amount: Number(l.amount) });
    }
    const entries = (await this.client.query('SELECT * FROM journal_entries ORDER BY id')).rows.map((r) => ({
      id: Number(r.id),
      date: r.date,
      description: r.description,
      department: r.department,
      purchaseId: r.purchase_id,
      voucherNo: r.voucher_no,
      postedBy: r.posted_by,
      entryType: r.entry_type || 'normal',
      status: r.status || 'active',
      ...(r.reverses_entry_id == null ? {} : { reversesEntryId: Number(r.reverses_entry_id) }),
      ...(r.reversed_by == null ? {} : { reversedBy: Number(r.reversed_by) }),
      ...(r.kaikei_entry_id == null ? {} : { kaikeiEntryId: Number(r.kaikei_entry_id) }),
      lines: linesByEntry.get(r.id) || [],
      createdAt: r.created_at,
    }));
    const pendingLinks = (await this.client.query('SELECT local_entry_id, payload FROM pending_links ORDER BY seq')).rows
      .map((r) => ({ localEntryId: Number(r.local_entry_id), payload: r.payload }));
    const users = (await this.client.query('SELECT code, name, role, active FROM users ORDER BY code')).rows
      .map((r) => ({ code: r.code, name: r.name, role: r.role, active: !!r.active }));
    const vendors = (await this.client.query('SELECT code, name FROM vendors ORDER BY code')).rows;
    const items = (await this.client.query('SELECT code, name, unit_price FROM items ORDER BY code')).rows
      .map((r) => ({ code: r.code, name: r.name, unitPrice: Number(r.unit_price) }));
    const changeHistory = (await this.client.query('SELECT id, target_id, changes, actor, reason, at FROM change_history ORDER BY id')).rows
      .map((r) => ({ id: Number(r.id), targetId: r.target_id, changes: r.changes, actor: r.actor, reason: r.reason, at: r.at }));
    const data = { purchases, payables, entries, pendingLinks, counters, users, vendors, items, changeHistory };
    const lastLinkError = (await this.client.query('SELECT value FROM meta WHERE key = $1', ['lastLinkError'])).rows[0];
    if (lastLinkError && lastLinkError.value != null) data.lastLinkError = lastLinkError.value;
    this.data = data;
  }

  // ユーザーマスタ（アクティブのみ。UI の操作者選択・表示名解決に使う）
  listUsers({ includeInactive = false } = {}) {
    let users = this.data.users || [];
    if (!includeInactive) users = users.filter((u) => u.active);
    return users.map((u) => ({ ...u }));
  }

  /* ---------- マスタ管理（v6 ステップ 8） ---------- */

  listVendors() {
    return (this.data.vendors || []).map((v) => ({ ...v }));
  }

  // 仕入先を追加する（コードは省略時自動採番。表記揺れ防止のためマスタ登録を一意に保つ）
  async addVendor({ code, name }) {
    if (!name || typeof name !== 'string' || !name.trim()) {
      throw new ValidationError('vendor name is required');
    }
    let vendorCode = code && String(code).trim();
    if (!vendorCode) {
      const maxNo = (this.data.vendors || []).reduce((m, v) => Math.max(m, Number(v.code.replace(/^V/, '')) || 0), 0);
      vendorCode = `V${String(maxNo + 1).padStart(3, '0')}`;
    }
    if ((this.data.vendors || []).some((v) => v.code === vendorCode)) {
      throw new ValidationError(`vendor code already exists: ${vendorCode}`);
    }
    await this.client.query('INSERT INTO vendors (code, name) VALUES ($1, $2) ON CONFLICT (code) DO NOTHING', [vendorCode, name.trim()]);
    this.data.vendors.push({ code: vendorCode, name: name.trim() });
    this.data.vendors.sort((a, b) => (a.code < b.code ? -1 : 1));
    return { code: vendorCode, name: name.trim() };
  }

  listItems() {
    return (this.data.items || []).map((i) => ({ ...i }));
  }

  async addItem({ code, name, unitPrice }) {
    if (!name || typeof name !== 'string' || !name.trim()) {
      throw new ValidationError('item name is required');
    }
    if (unitPrice != null && (!Number.isInteger(unitPrice) || unitPrice < 0)) {
      throw new ValidationError('unitPrice must be a non-negative integer');
    }
    let itemCode = code && String(code).trim();
    if (!itemCode) {
      const maxNo = (this.data.items || []).reduce((m, i) => Math.max(m, Number(i.code.replace(/^I/, '')) || 0), 0);
      itemCode = `I${String(maxNo + 1).padStart(3, '0')}`;
    }
    if ((this.data.items || []).some((i) => i.code === itemCode)) {
      throw new ValidationError(`item code already exists: ${itemCode}`);
    }
    const price = unitPrice == null ? 0 : unitPrice;
    await this.client.query('INSERT INTO items (code, name, unit_price) VALUES ($1, $2, $3) ON CONFLICT (code) DO NOTHING', [itemCode, name.trim(), price]);
    this.data.items.push({ code: itemCode, name: name.trim(), unitPrice: price });
    this.data.items.sort((a, b) => (a.code < b.code ? -1 : 1));
    return { code: itemCode, name: name.trim(), unitPrice: price };
  }

  // メモリ → DB。pg は非同期のため save が入れ子で走り得る（例: receive の保存中に
  // syncPending の保存が割り込む）— 同一クライアント上で交错すると DELETE+INSERT が
  // 干渉して主キー衝突する。v4 までの同期 SQLite では起き得なかった。
  // → キューで直列化し「常にメモリの最新状態を 1 トランザクションで書く」に戻す。
  #saveQueue = Promise.resolve();

  #save() {
    const run = this.#saveQueue.then(() => this.#saveNow());
    this.#saveQueue = run.catch(() => {}); // 失敗しても列は継続
    return run;
  }

  // メモリ → DB の実体。購買・支払予定・仕訳台帳・Outbox キューを 1 トランザクションで書き込む
  // （v2 からの「同じ書き込み時に保存」の整合性保証をそのまま維持）
  async #saveNow() {
    const d = this.data;
    const c = this.client;
    await c.query('BEGIN');
    try {
      const putCounter = 'INSERT INTO counters (name, value) VALUES ($1, $2) ON CONFLICT (name) DO UPDATE SET value = EXCLUDED.value';
      for (const [name, value] of Object.entries(d.counters)) await c.query(putCounter, [name, value]);

      const putPurchase = `INSERT INTO purchases
        (id, item, qty, unit_price, amount, requester, department, note, status, order_no, received_total, journal, history, correction, vendor_code, item_code, created_at)
        VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)
        ON CONFLICT (id) DO UPDATE SET
          item=EXCLUDED.item, qty=EXCLUDED.qty, unit_price=EXCLUDED.unit_price, amount=EXCLUDED.amount,
          requester=EXCLUDED.requester, department=EXCLUDED.department, note=EXCLUDED.note,
          status=EXCLUDED.status, order_no=EXCLUDED.order_no, received_total=EXCLUDED.received_total,
          journal=EXCLUDED.journal, history=EXCLUDED.history, correction=EXCLUDED.correction,
          vendor_code=EXCLUDED.vendor_code, item_code=EXCLUDED.item_code, created_at=EXCLUDED.created_at`;
      for (const p of d.purchases) {
        await c.query(putPurchase, [p.id, p.item, p.qty, p.unitPrice, p.amount, p.requester, p.department,
          p.note, p.status, p.orderNo, p.receivedTotal, JSON.stringify(p.journal), JSON.stringify(p.history),
          p.correction ? JSON.stringify(p.correction) : null, p.vendorCode ?? null, p.itemCode ?? null, p.createdAt]);
      }

      const putPayable = `INSERT INTO payables
        (id, purchase_id, purchase_item, department, received_qty, amount, received_date, scheduled_date, status, entry_id, created_at, paid_at)
        VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
        ON CONFLICT (id) DO UPDATE SET
          purchase_id=EXCLUDED.purchase_id, purchase_item=EXCLUDED.purchase_item, department=EXCLUDED.department,
          received_qty=EXCLUDED.received_qty, amount=EXCLUDED.amount, received_date=EXCLUDED.received_date,
          scheduled_date=EXCLUDED.scheduled_date, status=EXCLUDED.status, entry_id=EXCLUDED.entry_id,
          created_at=EXCLUDED.created_at, paid_at=EXCLUDED.paid_at`;
      for (const y of d.payables) {
        await c.query(putPayable, [y.id, y.purchaseId, y.purchaseItem, y.department, y.receivedQty, y.amount,
          y.receivedDate ?? null, y.scheduledDate, y.status, y.entryId, y.createdAt, y.paidAt]);
      }

      const putEntry = `INSERT INTO journal_entries (id, date, description, department, purchase_id, voucher_no, posted_by, entry_type, status, reverses_entry_id, reversed_by, kaikei_entry_id, created_at)
        VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
        ON CONFLICT (id) DO UPDATE SET date=EXCLUDED.date, description=EXCLUDED.description,
          department=EXCLUDED.department, purchase_id=EXCLUDED.purchase_id, voucher_no=EXCLUDED.voucher_no,
          posted_by=EXCLUDED.posted_by, entry_type=EXCLUDED.entry_type, status=EXCLUDED.status,
          reverses_entry_id=EXCLUDED.reverses_entry_id, reversed_by=EXCLUDED.reversed_by,
          kaikei_entry_id=EXCLUDED.kaikei_entry_id, created_at=EXCLUDED.created_at`;
      const putLine = 'INSERT INTO journal_lines (entry_id, seq, account_code, side, amount) VALUES ($1,$2,$3,$4,$5) ON CONFLICT (entry_id, seq) DO UPDATE SET account_code=EXCLUDED.account_code, side=EXCLUDED.side, amount=EXCLUDED.amount';
      for (const e of d.entries) {
        await c.query(putEntry, [e.id, e.date, e.description, e.department, e.purchaseId ?? null, e.voucherNo ?? null,
          e.postedBy ?? null, e.entryType || 'normal', e.status || 'active', e.reversesEntryId ?? null,
          e.reversedBy ?? null, e.kaikeiEntryId ?? null, e.createdAt]);
        for (const [seq, l] of e.lines.entries()) await c.query(putLine, [e.id, seq, l.account_code, l.side, l.amount]);
      }

      // Outbox キューは順序ごと差し替え（shift で先頭を消すため）
      await c.query('DELETE FROM pending_links');
      const putLink = 'INSERT INTO pending_links (seq, local_entry_id, payload) VALUES ($1,$2,$3)';
      for (const [seq, job] of d.pendingLinks.entries()) await c.query(putLink, [seq, job.localEntryId, JSON.stringify(job.payload)]);

      await c.query("INSERT INTO meta (key, value) VALUES ($1, $2) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value",
        ['lastLinkError', d.lastLinkError ? JSON.stringify(d.lastLinkError) : null]);

      await c.query('COMMIT');
    } catch (err) {
      await c.query('ROLLBACK');
      throw err;
    }
  }

  // v3 以前の purchases.json → PG の 1 回だけの移行（DB が空のときだけ）
  async #migrateJsonIfFresh() {
    if (this.data.purchases.length > 0 || this.data.entries.length > 0) return;
    let data;
    try {
      data = JSON.parse(fs.readFileSync(path.join(this.dataDir, 'purchases.json'), 'utf8'));
    } catch {
      return; // 初回起動時はファイルが無い
    }
    if (!Array.isArray(data.purchases)) return;
    if (!Array.isArray(data.entries)) data.entries = []; // v1 からの移行
    if (!Array.isArray(data.pendingLinks)) data.pendingLinks = []; // v3: 未同期キュー
    if (!data.counters || data.counters.entry == null) data.counters = { purchase: 0, order: 0, payable: 0, entry: 0 };
    this.data = {
      purchases: data.purchases,
      payables: Array.isArray(data.payables) ? data.payables : [],
      entries: data.entries,
      pendingLinks: data.pendingLinks,
      counters: data.counters,
      ...(data.lastLinkError ? { lastLinkError: data.lastLinkError } : {}),
    };
    await this.#save();
    console.error(`purchases.json から PostgreSQL (database: ${process.env.PG_DATABASE || 'purchase'}) への移行が完了しました`);
  }

  create({ item, qty, unitPrice, requester, department, note, vendorCode, itemCode }) {
    if (!item || typeof item !== 'string' || !item.trim()) {
      throw new ValidationError('item is required');
    }
    if (!Number.isInteger(qty) || qty < 1) {
      throw new ValidationError('qty must be an integer >= 1');
    }
    if (typeof unitPrice !== 'number' || unitPrice < 0 || Number.isNaN(unitPrice)) {
      throw new ValidationError('unitPrice must be a number >= 0');
    }
    if (!requester || typeof requester !== 'string' || !requester.trim()) {
      throw new ValidationError('requester is required');
    }
    // v6 ステップ 1: 申請者はユーザーマスタのコードで受ける（表記揺れ防止）
    const requesterUser = (this.data.users || []).find((u) => u.code === requester.trim() && u.active);
    if (!requesterUser) {
      throw new ValidationError(`unknown requester: ${requester}`);
    }
    // v6 ステップ 8: 仕入先・品目はマスタのコードで受ける（指定時のみ検証。UI は選択必須）
    let vendor = null;
    if (vendorCode != null && vendorCode !== '') {
      vendor = (this.data.vendors || []).find((v) => v.code === vendorCode);
      if (!vendor) throw new ValidationError(`unknown vendor: ${vendorCode}`);
    }
    let itemMaster = null;
    if (itemCode != null && itemCode !== '') {
      itemMaster = (this.data.items || []).find((i) => i.code === itemCode);
      if (!itemMaster) throw new ValidationError(`unknown item: ${itemCode}`);
    }
    if (department != null && !DEPARTMENTS.includes(department)) {
      throw new ValidationError(`department must be one of ${DEPARTMENTS.join('/')}`);
    }
    this.data.counters.purchase += 1;
    const id = `PU-${String(this.data.counters.purchase).padStart(4, '0')}`;
    const purchase = {
      id,
      item: item.trim(),
      qty,
      unitPrice,
      amount: qty * unitPrice,
      requester: requesterUser.code, // ユーザーコードで保存（表示名は listUsers 解決）
      vendorCode: vendor ? vendor.code : null,
      itemCode: itemMaster ? itemMaster.code : null,
      department: department || 'D90', // AC-001-02: 既定 D90（管理部・共通）
      note: note || '',
      status: 'submitted',
      orderNo: null,
      receivedTotal: 0,
      journal: [], // 仕訳参照: { kind, entryId, qty?, amount, date }（NFR-003）
      createdAt: now(),
      history: [
        { from: null, to: 'submitted', at: now(), actor: requesterUser.code, comment: '購買申請登録' },
      ],
    };
    this.data.purchases.push(purchase);
    return this.#save().then(() => purchase);
  }

  list(status) {
    if (status) {
      return this.data.purchases.filter((p) => p.status === status);
    }
    return this.data.purchases;
  }

  // 申請日などの履歴から日付を取り出す（YYYY-MM-DD 部分のみ比較に使う）
  #dateOf(purchase, toStatus, fromStatus = null) {
    const h = purchase.history.find((h) => h.to === toStatus && (fromStatus == null || h.from === fromStatus || h.from === null || h.from === h.to));
    return h ? h.at.slice(0, 10) : null;
  }

  // 購買 1 件を一覧表示用に拡張する（申請日・発注日・検収日・支払予定日を派生）
  #enrichPurchase(p) {
    const relatedPayables = this.data.payables.filter((y) => y.purchaseId === p.id);
    const scheduled = relatedPayables.filter((y) => y.status === 'scheduled').map((y) => y.scheduledDate).sort();
    const receiveEvents = p.history.filter((h) => h.receivedAt != null);
    const relatedPayablesAll = relatedPayables.filter((y) => y.receivedDate);
    const vendor = p.vendorCode ? (this.data.vendors || []).find((v) => v.code === p.vendorCode) : null;
    return {
      ...p,
      requestedDate: (p.createdAt || '').slice(0, 10),
      orderDate: this.#dateOf(p, 'ordered'),
      receiveDate: relatedPayablesAll.length > 0
        ? relatedPayablesAll[relatedPayablesAll.length - 1].receivedDate
        : (receiveEvents.length > 0 ? receiveEvents[receiveEvents.length - 1].receivedAt : null),
      scheduledDate: scheduled[0] || null,
      vendorCode: p.vendorCode || null,
      vendorName: vendor ? vendor.name : null,
    };
  }

  // v6 ステップ 6: 購買一覧の複合検索
  listPurchases({ q, requester, department, vendor, item, status, requestedFrom, requestedTo, orderFrom, orderTo, receiveFrom, receiveTo, scheduledFrom, scheduledTo } = {}) {
    return this.data.purchases
      .filter((p) => {
        if (status && p.status !== status) return false;
        if (requester && p.requester !== requester) return false;
        if (department && p.department !== department) return false;
        if (vendor && p.vendorCode !== vendor) return false;
        if (item && !(p.item || '').includes(item)) return false;
        if (q && !`${p.id} ${p.item} ${p.note || ''} ${p.orderNo || ''}`.includes(q)) return false;
        return true;
      })
      .map((p) => this.#enrichPurchase(p))
      .filter((e) => {
        if (requestedFrom && (!e.requestedDate || e.requestedDate < requestedFrom)) return false;
        if (requestedTo && (!e.requestedDate || e.requestedDate > requestedTo)) return false;
        if (orderFrom && (!e.orderDate || e.orderDate < orderFrom)) return false;
        if (orderTo && (!e.orderDate || e.orderDate > orderTo)) return false;
        if (receiveFrom && (!e.receiveDate || e.receiveDate < receiveFrom)) return false;
        if (receiveTo && (!e.receiveDate || e.receiveDate > receiveTo)) return false;
        if (scheduledFrom && (!e.scheduledDate || e.scheduledDate < scheduledFrom)) return false;
        if (scheduledTo && (!e.scheduledDate || e.scheduledDate > scheduledTo)) return false;
        return true;
      });
  }

  get(id) {
    const purchase = this.data.purchases.find((p) => p.id === id);
    if (!purchase) {
      throw new ValidationError(`purchase not found: ${id}`);
    }
    // v6 ステップ 3/8: 変更履歴・仕入先名を添付する（詳細画面・仕訳詳細から参照）
    const vendor = purchase.vendorCode ? (this.data.vendors || []).find((v) => v.code === purchase.vendorCode) : null;
    return {
      ...purchase,
      vendorName: vendor ? vendor.name : null,
      changeHistory: this.data.changeHistory.filter((h) => h.targetId === id),
    };
  }

  listPayables(status) {
    const base = status
      ? this.data.payables.filter((x) => x.status === status)
      : this.data.payables;
    // v6 ステップ 7/8: 発注番号・検収日・仕入先を添えて返す
    return base.map((y) => {
      const p = this.data.purchases.find((x) => x.id === y.purchaseId);
      const vendor = p && p.vendorCode ? (this.data.vendors || []).find((v) => v.code === p.vendorCode) : null;
      return {
        ...y,
        orderNo: p ? p.orderNo : null,
        vendorCode: p ? p.vendorCode || null : null,
        vendorName: vendor ? vendor.name : null,
      };
    });
  }

  /* ---------- 仕訳一覧（v6 ステップ 4） ---------- */

  // API 連携状態の導出: kaikeiEntryId が付いた = 連携済み、Outbox キューに残っている = 未連携、
  // 業務エラーで破棄された = エラー（ステップ 10 で専用画面を作る。ここでは状態判定のみ）
  #linkState(entry) {
    if (entry.kaikeiEntryId != null) return 'linked';
    if (this.data.lastLinkError && this.data.lastLinkError.localEntryId === entry.id) return 'error';
    if (this.data.pendingLinks.some((pl) => pl.localEntryId === entry.id)) return 'unlinked';
    return 'unlinked';
  }

  listEntries({ from, to, account, department, q, state: linkState } = {}) {
    const accountNames = new Map(ACCOUNTS_MASTER_LIST.map((a) => [a.code, a.name]));
    return this.data.entries
      .filter((e) => {
        if (from && e.date < from) return false;
        if (to && e.date > to) return false;
        if (department && e.department !== department) return false;
        if (account && !e.lines.some((l) => l.account_code === account)) return false;
        if (q && !(`${e.id} ${e.description} ${e.purchaseId || ''} ${e.voucherNo || ''}`.includes(q))) return false;
        return true;
      })
      .filter((e) => (linkState ? this.#linkState(e) === linkState : true))
      .map((e) => {
        const debit = e.lines.find((l) => l.side === 'debit');
        const credit = e.lines.find((l) => l.side === 'credit');
        return {
          id: e.id,
          date: e.date,
          voucherNo: e.voucherNo || null,
          purchaseId: e.purchaseId || null,
          vendor: e.purchaseId
            ? (() => {
                const p = this.data.purchases.find((x) => x.id === e.purchaseId);
                if (!p || !p.vendorCode) return null;
                const v = (this.data.vendors || []).find((vv) => vv.code === p.vendorCode);
                return v ? `${v.code} ${v.name}` : p.vendorCode;
              })()
            : null,
          description: e.description,
          debitAccount: debit ? `${debit.account_code} ${accountNames.get(debit.account_code) || ''}` : null,
          creditAccount: credit ? `${credit.account_code} ${accountNames.get(credit.account_code) || ''}` : null,
          amount: e.lines.filter((l) => l.side === 'debit').reduce((s, l) => s + l.amount, 0),
          multiLine: e.lines.length > 2,
          lines: e.lines.map((l) => ({ ...l })),
          status: e.status || 'active',
          entryType: e.entryType || 'normal',
          reversesEntryId: e.reversesEntryId ?? null,
          reversedBy: e.reversedBy ?? null,
          postedBy: e.postedBy || null,
          linkState: this.#linkState(e),
          createdAt: e.createdAt,
        };
      });
  }

  getEntry(id) {
    const entry = this.data.entries.find((e) => e.id === id);
    if (!entry) {
      const err = new Error(`journal entry not found: ${id}`);
      err.code = 'not_found';
      throw err;
    }
    const purchase = entry.purchaseId ? this.data.purchases.find((p) => p.id === entry.purchaseId) : null;
    return {
      ...entry,
      linkState: this.#linkState(entry),
      purchase: purchase
        ? {
            id: purchase.id,
            item: purchase.item,
            status: purchase.status,
            requester: purchase.requester,
            amount: purchase.amount,
            changeHistory: this.data.changeHistory.filter((h) => h.targetId === purchase.id),
          }
        : null,
    };
  }

  #find(id) {
    const purchase = this.data.purchases.find((p) => p.id === id);
    if (!purchase) {
      const err = new Error(`purchase not found: ${id}`);
      err.code = 'not_found';
      throw err;
    }
    return purchase;
  }

  #push(purchase, from, to, actor, comment, extra) {
    purchase.status = to;
    purchase.history.push({ from, to, at: now(), actor: actor || '担当', comment: comment || '', ...extra });
  }

  // AC-002-01: 承認（1段）。submitted → approved。
  // v6 ステップ 2: 自己承認禁止 — 申請者本人（同じユーザーコード）は承認できない。
  approve(id, actor, comment) {
    const purchase = this.#find(id);
    if (purchase.status !== 'submitted') {
      throw new TransitionError('approve', purchase.status);
    }
    if (actor && purchase.requester === actor) {
      throw new SelfApprovalError();
    }
    this.#push(purchase, 'submitted', 'approved', actor, comment || '');
    return this.#save().then(() => purchase);
  }

  // AC-002-02: 却下（submitted のみ。コメント必須）
  reject(id, actor, comment) {
    if (!comment || !comment.trim()) {
      throw new ValidationError('comment is required to reject');
    }
    const purchase = this.#find(id);
    if (purchase.status !== 'submitted') {
      throw new TransitionError('reject', purchase.status);
    }
    this.#push(purchase, purchase.status, 'rejected', actor, comment.trim());
    return this.#save().then(() => purchase);
  }

  // AC-002-03: 再申請（rejected / withdrawn → submitted。履歴保持）
  resubmit(id, actor, comment) {
    const purchase = this.#find(id);
    if (purchase.status !== 'rejected' && purchase.status !== 'withdrawn') {
      throw new TransitionError('resubmit', purchase.status);
    }
    this.#push(purchase, purchase.status, 'submitted', actor, comment || '修正のうえ再申請', { resubmit: true });
    return this.#save().then(() => purchase);
  }

  // v6 ステップ 3: 取下げ（submitted → withdrawn）。申請者本人のみ。
  withdraw(id, actor) {
    const purchase = this.#find(id);
    if (purchase.status !== 'submitted') {
      throw new TransitionError('withdraw', purchase.status);
    }
    if (actor !== purchase.requester) {
      throw new ValidationError('only the requester can withdraw the purchase');
    }
    this.#push(purchase, 'submitted', 'withdrawn', actor, '取下げ（申請者による取り下げ）');
    return this.#save().then(() => purchase);
  }

  // v6 ステップ 3: 申請後の修正（直接上書きはしない。状態別に分岐・全変更を change_history に残す）
  //   withdrawn / rejected : 修正のみ（状態は動かない。その後 resubmit する）
  //   approved             : 変更申請 — 修正のうえ submitted に戻し、再承認を経る
  //   ordered              : 直接上書きせず変更履歴のみ残す（状態は動かない）
  //   received 以降         : 変更不可（訂正は取消仕訳・訂正仕訳のフロー・ステップ 5）
  async update(id, actor, updates, reason) {
    const purchase = this.#find(id);
    const editable = ['withdrawn', 'rejected', 'approved', 'ordered'];
    if (!editable.includes(purchase.status)) {
      throw new TransitionError('update', purchase.status);
    }
    if (!reason || !reason.trim()) {
      throw new ValidationError('reason is required to update');
    }
    const up = updates || {};
    const changes = [];
    const before = { item: purchase.item, qty: purchase.qty, unitPrice: purchase.unitPrice, department: purchase.department, note: purchase.note };

    const next = { ...before };
    if (up.item != null) {
      if (typeof up.item !== 'string' || !up.item.trim()) throw new ValidationError('item is required');
      next.item = up.item.trim();
    }
    if (up.qty != null) {
      if (!Number.isInteger(up.qty) || up.qty < 1) throw new ValidationError('qty must be a positive integer');
      next.qty = up.qty;
    }
    if (up.unitPrice != null) {
      if (!Number.isInteger(up.unitPrice) || up.unitPrice < 0) throw new ValidationError('unitPrice must be a non-negative integer');
      next.unitPrice = up.unitPrice;
    }
    if (up.department != null) {
      if (!DEPARTMENTS.includes(up.department)) throw new ValidationError(`department must be one of ${DEPARTMENTS.join('/')}`);
      next.department = up.department;
    }
    if (up.note != null) next.note = String(up.note);
    for (const key of Object.keys(before)) {
      if (next[key] !== before[key]) changes.push({ field: key, before: before[key], after: next[key] });
    }
    // 金額 = 数量 × 単価（数量・単価の変更に連動して再計算し、履歴にも残す）
    const nextAmount = next.qty * next.unitPrice;
    if (nextAmount !== purchase.amount) changes.push({ field: 'amount', before: purchase.amount, after: nextAmount });
    if (changes.length === 0) {
      throw new ValidationError('no changes to update');
    }

    for (const c of changes) purchase[c.field] = c.after;
    if (purchase.status === 'approved') {
      // 変更申請: 承認済みの内容を変えるので、再承認を経る（submitted に戻る）
      this.#push(purchase, 'approved', 'submitted', actor, `変更申請: ${reason.trim()}`);
    } else if (purchase.status === 'ordered') {
      // 発注済み: 直接上書きせず変更履歴を残す（状態は動かさない）
      this.#push(purchase, 'ordered', 'ordered', actor, `発注内容変更: ${reason.trim()}`, { change: true });
    } else {
      // withdrawn / rejected: 修正のみ（resubmit は別操作）
      this.#push(purchase, purchase.status, purchase.status, actor, `修正: ${reason.trim()}`, { change: true });
    }

    // 履歴は追記のみ（削除しない。変更前後・修正者・日時・理由を残す）
    const inserted = await this.client.query(
      'INSERT INTO change_history (target_id, changes, actor, reason, at) VALUES ($1, $2, $3, $4, $5) RETURNING id',
      [purchase.id, JSON.stringify(changes), actor, reason.trim(), now()],
    );
    this.data.changeHistory.push({
      id: Number(inserted.rows[0].id), targetId: purchase.id, changes, actor, reason: reason.trim(), at: now(),
    });
    await this.#save();
    return purchase;
  }

  // AC-003-01: 発注（approved のみ。遷移失敗時は採番 counter を消費しない）
  order(id, actor) {
    const purchase = this.#find(id);
    if (purchase.status !== 'approved') {
      throw new TransitionError('order', purchase.status);
    }
    this.data.counters.order += 1;
    const orderNo = `PO-${new Date().getFullYear()}-${String(this.data.counters.order).padStart(3, '0')}`;
    purchase.orderNo = orderNo;
    this.#push(purchase, 'approved', 'ordered', actor, `発注（発注番号: ${orderNo}）`);
    return this.#save().then(() => purchase);
  }

  // AC-004-01/03: 分割検収。検収 1 回ごとに (1) 仕訳 1 件を計上（借: 仕入高 / 貸: 買掛金）、
  // (2) 支払予定 1 件を計上する。全量検収で received（AC-004-02）。
  receive(id, actor, receivedQty, receivedAt, comment) {
    const purchase = this.#find(id);
    if (purchase.status !== 'ordered') {
      throw new TransitionError('receive', purchase.status);
    }
    const qty = receivedQty == null ? purchase.qty - purchase.receivedTotal : receivedQty;
    if (!Number.isInteger(qty) || qty < 1) {
      throw new ValidationError('receivedQty must be an integer >= 1');
    }
    if (purchase.receivedTotal + qty > purchase.qty) {
      throw new ValidationError(`receivedQty exceeds remaining (${purchase.qty - purchase.receivedTotal})`);
    }
    const amount = qty * purchase.unitPrice;
    if (!Number.isInteger(amount) || amount < 1) {
      throw new ValidationError(`amount (qty × unitPrice = ${amount}) must be an integer >= 1`);
    }
    const date = receivedAt || now().slice(0, 10);

    // 仕訳計上（借: 仕入高 5110 / 貸: 買掛金 2110）。v6: 元伝票 = 検収伝票（PU-xxxx-Rn）
    const receiptSeq = purchase.journal.filter((j) => j.kind === 'receive').length + 1;
    const entry = this.journal.post({
      date,
      department: purchase.department,
      description: `購買検収 ${purchase.id}（${purchase.item}）`,
      purchaseId: purchase.id,
      voucherNo: `${purchase.id}-R${receiptSeq}`,
      postedBy: actor,
      entryType: 'receive',
      lines: [
        { account_code: '5110', side: 'debit', amount },
        { account_code: '2110', side: 'credit', amount },
      ],
    });

    purchase.receivedTotal += qty;
    this.#push(purchase, 'ordered', purchase.receivedTotal === purchase.qty ? 'received' : 'ordered', actor,
      `検収（数量: ${qty} / 累計: ${purchase.receivedTotal}/${purchase.qty}）・仕訳 entry #${entry.id}`,
      { receivedQty: qty, receivedAt: date, entryId: entry.id });
    purchase.journal.push({ kind: 'receive', entryId: entry.id, qty, amount, date });

    // AC-005-01: 検収ごとに支払予定を計上（金額 = 検収数量 × 単価、支払予定日 = 検収月の翌月末日）
    this.data.counters.payable += 1;
    const payable = {
      id: `PAY-${String(this.data.counters.payable).padStart(4, '0')}`,
      purchaseId: purchase.id,
      purchaseItem: purchase.item,
      department: purchase.department,
      receivedQty: qty,
      amount,
      receivedDate: date,
      scheduledDate: nextMonthEnd(date),
      status: 'scheduled',
      entryId: null, // 支払実行時に支払仕訳の entry id を保存（AC-005-03）
      createdAt: now(),
      paidAt: null,
    };
    this.data.payables.push(payable);
    this.#enqueueLink(entry);
    return this.#save().then(() => {
      this.#trySyncPending().catch(() => {}); // ベストエフォート（失敗はキューに残る）
      return { purchase, payable };
    });
  }

  // AC-005-02/03: 支払予定単位で支払済み化（scheduled のみ）。
  // 仕訳 1 件を計上（借: 買掛金 / 貸: 普通預金）してから状態を更新する。
  pay(payableId, actor, comment) {
    const payable = this.data.payables.find((x) => x.id === payableId);
    if (!payable) {
      const err = new Error(`payable not found: ${payableId}`);
      err.code = 'not_found';
      throw err;
    }
    if (payable.status !== 'scheduled') {
      throw new TransitionError('pay', payable.status);
    }
    const purchase = this.data.purchases.find((p) => p.id === payable.purchaseId);

    // 仕訳計上（借: 買掛金 2110 / 貸: 普通預金 1120）。v6: 元伝票 = 支払予定（PAY-xxxx）
    const entry = this.journal.post({
      date: now().slice(0, 10),
      department: purchase ? purchase.department : 'D90',
      description: `購買支払 ${payable.purchaseId} / ${payable.id}`,
      purchaseId: payable.purchaseId,
      voucherNo: payable.id,
      postedBy: actor,
      entryType: 'pay',
      lines: [
        { account_code: '2110', side: 'debit', amount: payable.amount },
        { account_code: '1120', side: 'credit', amount: payable.amount },
      ],
    });

    payable.status = 'paid';
    payable.paidAt = now();
    payable.entryId = entry.id;
    if (purchase) {
      // v6 ステップ 5: 全支払予定の支払いが完了したら購買も paid へ（§7 支払状態更新）
      const allPaid = !this.data.payables.some((y) => y.purchaseId === purchase.id && y.status === 'scheduled');
      this.#push(purchase, purchase.status, allPaid ? 'paid' : purchase.status, actor,
        `支払実行（${payable.id}: ${payable.amount}円・仕訳 entry #${entry.id}）`, { entryId: entry.id });
      purchase.journal.push({ kind: 'pay', entryId: entry.id, payableId: payable.id, amount: payable.amount, date: now().slice(0, 10) });
    }
    this.#enqueueLink(entry);
    return this.#save().then(() => {
      this.#trySyncPending().catch(() => {}); // ベストエフォート
      return payable;
    });
  }

  /* ---------- 訂正申請・取消仕訳（v6 ステップ 5） ---------- */

  // 検収後（received / paid）の購買の訂正申請。直接編集はせず、承認を経てから
  // 「元処理の取消（取消仕訳）→ 正しい内容で再計上（訂正仕訳）」を行う（憲法 II・§4/§5）。
  // 訂正できるのは 品目・単価・備考 のみ（数量は検収実績なので訂正対象外）。
  requestCorrection(id, actor, updates, reason) {
    const purchase = this.#find(id);
    if (purchase.status !== 'received' && purchase.status !== 'paid') {
      throw new TransitionError('request-correction', purchase.status);
    }
    if (!reason || !reason.trim()) {
      throw new ValidationError('reason is required to request correction');
    }
    const up = updates || {};
    const changes = [];
    const next = { item: purchase.item, unitPrice: purchase.unitPrice, note: purchase.note };
    if (up.item != null) {
      if (typeof up.item !== 'string' || !up.item.trim()) throw new ValidationError('item is required');
      next.item = up.item.trim();
    }
    if (up.unitPrice != null) {
      if (!Number.isInteger(up.unitPrice) || up.unitPrice < 0) throw new ValidationError('unitPrice must be a non-negative integer');
      next.unitPrice = up.unitPrice;
    }
    if (up.note != null) next.note = String(up.note);
    for (const key of Object.keys(next)) {
      if (next[key] !== purchase[key]) changes.push({ field: key, before: purchase[key], after: next[key] });
    }
    if (changes.length === 0) {
      throw new ValidationError('no changes to correct');
    }
    // 承認待ちの間だけ申請内容を保持する（承認時に適用。却下なら破棄して元の状態へ戻す）
    purchase.correction = { updates: next, reason: reason.trim(), requestedBy: actor, requestedAt: now(), from: purchase.status };
    this.#push(purchase, purchase.status, 'correction_pending', actor, `訂正申請: ${reason.trim()}`, { change: true });
    return this.#save().then(() => purchase);
  }

  // 訂正申請の承認（申請者本人は不可）。承認時に取消仕訳 → 訂正仕訳を一括計上する。
  async approveCorrection(id, actor) {
    const purchase = this.#find(id);
    if (purchase.status !== 'correction_pending') {
      throw new TransitionError('approve-correction', purchase.status);
    }
    if (actor && purchase.requester === actor) {
      throw new SelfApprovalError();
    }
    const corr = purchase.correction;
    if (!corr) {
      throw new ValidationError('correction request not found');
    }
    const reason = corr.reason;

    // (1) 元処理の取消: この購買の有効な仕訳をすべて取消仕訳（逆仕訳）で消す。
    //    取消仕訳・元仕訳・訂正仕訳はすべて履歴として残る（§5・憲法 II: 直接編集・削除はしない）
    const targetEntries = this.data.entries.filter((e) => e.purchaseId === id && (e.status || 'active') === 'active');
    for (const e of targetEntries) {
      const reversal = this.journal.post({
        date: now().slice(0, 10),
        department: e.department,
        description: `仕訳 #${e.id} の取消（訂正: ${reason}）`,
        purchaseId: id,
        voucherNo: `${id}-REV${e.id}`,
        postedBy: actor,
        entryType: 'reversal',
        reversesEntryId: e.id,
        lines: e.lines.map((l) => ({ account_code: l.account_code, side: l.side === 'debit' ? 'credit' : 'debit', amount: l.amount })),
      });
      e.status = 'reversed';
      e.reversedBy = reversal.id;
      this.#enqueueLink(reversal);
    }

    // (2) 正しい内容で再計上: 訂正後の金額 = 検収済み数量 × 訂正後単価
    const appliedChanges = [];
    for (const [key, after] of Object.entries(corr.updates)) {
      appliedChanges.push({ field: key, before: purchase[key], after });
      purchase[key] = after;
    }
    purchase.amount = purchase.qty * purchase.unitPrice;
    const correctedAmount = purchase.receivedTotal * purchase.unitPrice;
    const newEntries = [];
    const receiveEntry = this.journal.post({
      date: now().slice(0, 10),
      department: purchase.department,
      description: `購買訂正 ${id}（訂正後: ${purchase.receivedTotal} × ¥${purchase.unitPrice}）`,
      purchaseId: id,
      voucherNo: `${id}-CORR`,
      postedBy: actor,
      entryType: 'correction',
      lines: [
        { account_code: '5110', side: 'debit', amount: correctedAmount },
        { account_code: '2110', side: 'credit', amount: correctedAmount },
      ],
    });
    newEntries.push(receiveEntry);
    // 支払済みだった場合は支払仕訳も再計上（借: 買掛金 / 貸: 普通預金）
    let payEntry = null;
    if (corr.from === 'paid') {
      payEntry = this.journal.post({
        date: now().slice(0, 10),
        department: purchase.department,
        description: `購買支払（訂正後） ${id}`,
        purchaseId: id,
        voucherNo: `${id}-CORRPAY`,
        postedBy: actor,
        entryType: 'correction',
        lines: [
          { account_code: '2110', side: 'debit', amount: correctedAmount },
          { account_code: '1120', side: 'credit', amount: correctedAmount },
        ],
      });
      newEntries.push(payEntry);
    }

    // (3) 支払予定も訂正後の単価で揃える（検収数量 × 新単価）
    for (const y of this.data.payables) {
      if (y.purchaseId === id) {
        y.amount = y.receivedQty * purchase.unitPrice;
        if (y.status === 'paid' && payEntry) y.entryId = payEntry.id;
      }
    }

    // 履歴: 変更履歴（変更前後・修正者・日時・理由）+ 遷移履歴 + 仕訳参照を更新して元の状態へ戻す
    const histInserted = await this.client.query(
      'INSERT INTO change_history (target_id, changes, actor, reason, at) VALUES ($1, $2, $3, $4, $5) RETURNING id',
      [id, JSON.stringify(appliedChanges), actor, `訂正承認: ${reason}`, now()],
    );
    this.data.changeHistory.push({
      id: Number(histInserted.rows[0].id), targetId: id, changes: appliedChanges, actor, reason: `訂正承認: ${reason}`, at: now(),
    });
    this.#push(purchase, 'correction_pending', corr.from, actor,
      `訂正承認・再計上（取消仕訳 ${targetEntries.length} 件・訂正仕訳 ${newEntries.length} 件）`,
      { entryId: receiveEntry.id });
    purchase.journal.push({ kind: 'receive', entryId: receiveEntry.id, amount: correctedAmount, date: now().slice(0, 10), correction: true });
    if (payEntry) {
      purchase.journal.push({ kind: 'pay', entryId: payEntry.id, amount: correctedAmount, date: now().slice(0, 10), correction: true });
    }
    purchase.correction = null; // 承認済みなので保持を消す

    for (const e of newEntries) this.#enqueueLink(e);
    await this.#save();
    this.#trySyncPending().catch(() => {});
    return purchase;
  }

  /* ---------- kaikei-api ミラー連携（v3・Outbox 方式） ---------- */

  // 仕訳をミラー送信キューに入れる（payload は kaikei-api 契約 §3 の形式そのまま）
  #enqueueLink(entry) {
    this.data.pendingLinks.push({
      localEntryId: entry.id,
      payload: {
        date: entry.date,
        description: entry.description,
        department: entry.department,
        lines: entry.lines.map((l) => ({ account_code: l.account_code, side: l.side, amount: l.amount })),
      },
    });
  }

  // キュー内の未送信仕訳を kaikei-api へ送る。1 件でも接続不可なら残りを残して中断。
  // 成功した仕訳には kaikeiEntryId（向こう側の採番 id）を記録する。
  // 同時呼び出しはスキップではなく直列化して待たせる（receive・pay のベストエフォート
  // 送信とテスト等の明示呼び出しが競合しても、await した呼び出しは必ず自前の 1 巡を行う）。
  #syncQueue = Promise.resolve();

  syncPending() {
    const run = this.#syncQueue.then(() => this.#syncNow());
    this.#syncQueue = run.catch(() => {}); // 失敗しても列は継続
    return run;
  }

  async #syncNow() {
    let sent = 0;
    while (this.data.pendingLinks.length > 0) {
      const job = this.data.pendingLinks[0];
      try {
        const remote = await this.kaikei.postEntry(job.payload);
        const entry = this.data.entries.find((e) => e.id === job.localEntryId);
        if (entry) entry.kaikeiEntryId = remote.id;
        this.data.pendingLinks.shift();
        sent += 1;
      } catch (err) {
        if (err.code === 'kaikei_unavailable') break; // 相手が居ない → 後で再送
        // kaikei 側の業務エラー（未知科目など）は再送しても届かないので破棄して記録
        this.data.pendingLinks.shift();
        this.data.lastLinkError = { at: now(), localEntryId: job.localEntryId, message: err.message };
      }
    }
    await this.#save();
    return { sent, remaining: this.data.pendingLinks.length, ...this.syncStatus() };
  }

  syncStatus() {
    return {
      enabled: true,
      url: this.kaikei.baseUrl,
      pending: this.data.pendingLinks.length,
      lastError: this.data.lastLinkError || null,
    };
  }

  // 操作のたびにベストエフォートで送る（失敗は握りつぶし・キューに残す）
  async #trySyncPending() {
    try {
      await this.syncPending();
    } catch (err) {
      this.data.lastLinkError = { at: now(), message: err.message };
    }
  }

  /* ---------- 自動再送タイマー ---------- */

  // Outbox キューに残りがある間、定間隔で自動再送する（相手が復帰したら
  // 検収・支払を待たずに追いつく。unref なのでプロセスの終了を妨げない）
  startAutoSync(intervalMs = 30_000) {
    this.stopAutoSync();
    this._autoSyncTimer = setInterval(() => {
      if (this.data.pendingLinks.length > 0) this.#trySyncPending();
    }, intervalMs);
    this._autoSyncTimer.unref();
    // 起動直後にも 1 回：前回の未送信分をできるだけ早く回収する
    if (this.data.pendingLinks.length > 0) this.#trySyncPending();
  }

  stopAutoSync() {
    if (this._autoSyncTimer) {
      clearInterval(this._autoSyncTimer);
      this._autoSyncTimer = null;
    }
  }

  // PG 接続・タイマーを閉じる（テストの後始末用。サーバー本番では呼ばない）
  async close() {
    this.stopAutoSync();
    PurchaseStore.#live.delete(this);
    try {
      await this.client.end();
    } catch {
      // すでに切れている場合は無視
    }
  }

  // 生成済みの全インスタンスを一括 close（node --test の after フックから使う）
  static async closeAll() {
    await Promise.allSettled([...PurchaseStore.#live].map((s) => s.close()));
  }
}

module.exports = {
  PurchaseStore,
  SelfApprovalError,
  TransitionError,
  ValidationError,
  STATUSES,
  DEPARTMENTS,
  nextMonthEnd,
};
